In [4]:
import numpy as np

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [27]:
array1 = np.array(range(30)).reshape((5,6), order = "F")
print(array1)

[[ 0  5 10 15 20 25]
 [ 1  6 11 16 21 26]
 [ 2  7 12 17 22 27]
 [ 3  8 13 18 23 28]
 [ 4  9 14 19 24 29]]


In [29]:
array2 = np.where(array1 % 6 == 1)
print(array2)

(array([0, 1, 2, 3, 4]), array([5, 0, 1, 2, 3]))
