In [3]:
import numpy as np

In [27]:
array1 = np.array(range(30)).reshape((5,6), order = "F")
print(array1)

[[ 0  5 10 15 20 25]
 [ 1  6 11 16 21 26]
 [ 2  7 12 17 22 27]
 [ 3  8 13 18 23 28]
 [ 4  9 14 19 24 29]]


In [29]:
array2 = np.where(array1 % 6 == 1)
print(array2)

(array([0, 1, 2, 3, 4]), array([5, 0, 1, 2, 3]))


In [7]:
#問題一

array2 = np.array(range(10))
print(array2)
print(type(array2))
print(array2.dtype)

"""
type語法指的是我們自定義變數的資料型態為何
dtype語法指的是我們自定義變數內資料的資料型態為何
"""

[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>
int64


'\n問題一：\n\ntype語法指的是我們自定義變數的資料型態為何\ndtype語法指的是我們自定義變數內資料的資料型態為何\n'

In [12]:
#問題二

def is_dtype(a, t):
    bool_value = (a.dtype == t)
    return bool_value

print(is_dtype(array2, 'int64'))

True


In [ ]:
#問題三

def is_dtype(a, t):
    return a.dtype is t
#要寫成 a.dtype is np.dtype(t)

def is_dtype(a, t):
    return type(a) == np.dtype(t)
#type和dtype所代表的東西不一樣

def is_dtype(a, t):
    return type(a) is np.dtype(t)
#type和dtype所代表的東西不一樣

