In [1]:
import numpy as np

In [6]:
zero = np.zeros((2, 3))
empty = np.empty((2, 3))
print(zero)
print(empty)

[[0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 0. 0.]]


In [11]:
a = np.random.rand(2, 3)
print(a)
b = np.around(a)
print(b)

[[0.48456572 0.68373478 0.66861923]
 [0.68184911 0.76958314 0.37489386]]
[[0. 1. 1.]
 [1. 1. 0.]]


In [22]:
m = 3
n = 7
a = np.random.rand(2, 3)
c = np.clip(a, m, n)
print(c)

[[3. 3. 3.]
 [3. 3. 3.]]


In [34]:
name_list = ['小明','小華','小菁','小美','小張','John','Mark','Tom']
sex_list = ['boy','boy','girl','girl','boy','boy','boy','boy']
weight_list = [67.5,75.3,50.1,45.5,80.8,90.4,78.4,70.7]
rank_list = [8,1,5,4,7,6,2,3]
myopia_list = [True,True,False,False,True,True,False,False]

#[Unicode,Unicode,float,int,boolean]

In [36]:
dt = np.dtype({'names':('name', 'sex', 'weight', 'rank', 'myopia'),
               'formats':('U8', 'U8', float, int, bool)})
structured = np.zeros(8, dtype = dt)
structured['name'] = name_list
structured['sex'] = sex_list
structured['weight'] = weight_list
structured['rank'] = rank_list
structured['myopia'] = myopia_list

print(structured)

[('小明', 'boy', 67.5, 8,  True) ('小華', 'boy', 75.3, 1,  True)
 ('小菁', 'girl', 50.1, 5, False) ('小美', 'girl', 45.5, 4, False)
 ('小張', 'boy', 80.8, 7,  True) ('John', 'boy', 90.4, 6,  True)
 ('Mark', 'boy', 78.4, 2, False) ('Tom', 'boy', 70.7, 3, False)]


In [38]:
total = 0
num = 0
for weight in structured['weight']:
    total += weight
    num += 1

avg = total / num
print(avg)
    

[67.5 75.3 50.1 45.5 80.8 90.4 78.4 70.7]
69.8375


In [44]:
boy_w = structured[structured['sex'] == 'boy']['weight']

total = 0
num = 0
for weight in boy_w:
    total += weight
    num += 1

avg = total / num
print(avg)

77.18333333333332


In [46]:
girl_w = structured[structured['sex'] == 'girl']['weight']

total = 0
num = 0
for weight in girl_w:
    total += weight
    num += 1

avg = total / num
print(avg)

47.8
