In [2]:
import numpy as np

In [10]:
a = np.random.random((5, 5))
print(a)
amin, amax = a.min(), a.max()
a = (a - amin)/(amax - amin)
print('--------')
print(a)

[[0.74636356 0.13321736 0.30518052 0.77914206 0.69920945]
 [0.95217361 0.7687846  0.92646832 0.28214074 0.24310549]
 [0.23098334 0.61523924 0.96686137 0.76566491 0.33184357]
 [0.27221016 0.43412045 0.01832965 0.92506589 0.03099184]
 [0.72290283 0.5625859  0.65213577 0.43575499 0.99489689]]
--------
[[0.74550311 0.11764444 0.29373387 0.77906813 0.69721753]
 [0.95625157 0.76846214 0.92992948 0.27014124 0.23016934]
 [0.21775632 0.61123246 0.97129177 0.76526759 0.3210367 ]
 [0.25997238 0.42576771 0.         0.9284934  0.01296602]
 [0.72147943 0.55731569 0.64901432 0.42744147 1.        ]]


In [20]:
a = np.random.randint(1,50,10)
print(a)
max_index = np.argmax(a)
print(b)
a[max_index] = -1
print(a)

[39 45 39 20 35  8  5 37 46 31]
5
[39 45 39 20 35  8  5 37 -1 31]


In [22]:
array1 = np.array(range(30))
print(array1)
array_new = array1.reshape((5, 6), order = 'F')
print(array_new)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
[[ 0  5 10 15 20 25]
 [ 1  6 11 16 21 26]
 [ 2  7 12 17 22 27]
 [ 3  8 13 18 23 28]
 [ 4  9 14 19 24 29]]


In [23]:
b = array_new[array_new % 6 == 1]
print(b)

[25  1  7 13 19]
