In [31]:
import numpy as np
import timeit

In [49]:
z = np.random.randint(0, 10, 1000000).reshape(100, 100, 100)

%timeit -n 10 a = 2
z + 1

42.3 ns ± 13.9 ns per loop (mean ± std. dev. of 7 runs, 10 loops each)


array([[[ 2,  3, 10, ...,  5,  6,  2],
        [ 5, 10,  3, ...,  7,  3,  6],
        [ 9,  1,  1, ...,  6,  1,  1],
        ...,
        [ 6,  3,  2, ...,  5,  3,  9],
        [ 3,  5,  8, ..., 10,  8,  6],
        [ 7,  4,  9, ...,  5,  1,  1]],

       [[ 8,  3,  8, ...,  2,  1,  2],
        [ 1,  5,  7, ...,  1,  2,  5],
        [ 5,  8,  9, ...,  7,  7,  7],
        ...,
        [ 5, 10,  1, ...,  6,  4,  8],
        [ 3,  3,  8, ...,  1,  8,  2],
        [ 8,  7, 10, ...,  6,  8,  7]],

       [[ 4,  8,  5, ...,  4,  5,  2],
        [ 7,  8,  3, ...,  8,  7,  5],
        [ 9,  6,  5, ...,  4,  7,  9],
        ...,
        [ 9, 10,  2, ...,  7,  3,  2],
        [ 5,  5,  1, ..., 10,  7,  2],
        [ 5,  1,  9, ...,  4,  3,  6]],

       ...,

       [[ 9,  9,  9, ...,  8, 10,  9],
        [ 2, 10, 10, ...,  2,  8,  8],
        [10,  8,  6, ...,  3,  5,  1],
        ...,
        [ 1,  6,  8, ...,  1,  5,  4],
        [10,  9,  6, ...,  9,  3,  3],
        [ 7,  9, 10, ...,  6,  3

In [50]:
global z
def plus_one():
    z1 = z + 1
    return z1

%timeit -n 10 a = 2
plus_one()

50.7 ns ± 15.5 ns per loop (mean ± std. dev. of 7 runs, 10 loops each)


array([[[ 2,  3, 10, ...,  5,  6,  2],
        [ 5, 10,  3, ...,  7,  3,  6],
        [ 9,  1,  1, ...,  6,  1,  1],
        ...,
        [ 6,  3,  2, ...,  5,  3,  9],
        [ 3,  5,  8, ..., 10,  8,  6],
        [ 7,  4,  9, ...,  5,  1,  1]],

       [[ 8,  3,  8, ...,  2,  1,  2],
        [ 1,  5,  7, ...,  1,  2,  5],
        [ 5,  8,  9, ...,  7,  7,  7],
        ...,
        [ 5, 10,  1, ...,  6,  4,  8],
        [ 3,  3,  8, ...,  1,  8,  2],
        [ 8,  7, 10, ...,  6,  8,  7]],

       [[ 4,  8,  5, ...,  4,  5,  2],
        [ 7,  8,  3, ...,  8,  7,  5],
        [ 9,  6,  5, ...,  4,  7,  9],
        ...,
        [ 9, 10,  2, ...,  7,  3,  2],
        [ 5,  5,  1, ..., 10,  7,  2],
        [ 5,  1,  9, ...,  4,  3,  6]],

       ...,

       [[ 9,  9,  9, ...,  8, 10,  9],
        [ 2, 10, 10, ...,  2,  8,  8],
        [10,  8,  6, ...,  3,  5,  1],
        ...,
        [ 1,  6,  8, ...,  1,  5,  4],
        [10,  9,  6, ...,  9,  3,  3],
        [ 7,  9, 10, ...,  6,  3

In [51]:
for row in z:
    for num in row:
        num += 1

%timeit -n 10 a = 2
z

43.6 ns ± 15 ns per loop (mean ± std. dev. of 7 runs, 10 loops each)


array([[[ 2,  3, 10, ...,  5,  6,  2],
        [ 5, 10,  3, ...,  7,  3,  6],
        [ 9,  1,  1, ...,  6,  1,  1],
        ...,
        [ 6,  3,  2, ...,  5,  3,  9],
        [ 3,  5,  8, ..., 10,  8,  6],
        [ 7,  4,  9, ...,  5,  1,  1]],

       [[ 8,  3,  8, ...,  2,  1,  2],
        [ 1,  5,  7, ...,  1,  2,  5],
        [ 5,  8,  9, ...,  7,  7,  7],
        ...,
        [ 5, 10,  1, ...,  6,  4,  8],
        [ 3,  3,  8, ...,  1,  8,  2],
        [ 8,  7, 10, ...,  6,  8,  7]],

       [[ 4,  8,  5, ...,  4,  5,  2],
        [ 7,  8,  3, ...,  8,  7,  5],
        [ 9,  6,  5, ...,  4,  7,  9],
        ...,
        [ 9, 10,  2, ...,  7,  3,  2],
        [ 5,  5,  1, ..., 10,  7,  2],
        [ 5,  1,  9, ...,  4,  3,  6]],

       ...,

       [[ 9,  9,  9, ...,  8, 10,  9],
        [ 2, 10, 10, ...,  2,  8,  8],
        [10,  8,  6, ...,  3,  5,  1],
        ...,
        [ 1,  6,  8, ...,  1,  5,  4],
        [10,  9,  6, ...,  9,  3,  3],
        [ 7,  9, 10, ...,  6,  3

In [58]:
z = np.random.randint(0,10,50)
print(z)

max_freq = np.argmax(z)
print(max_freq)
print(z[max_freq]) #數值
a = np.where(z == z[max_freq]) #位置
print(a)

[9 2 2 0 9 4 2 6 9 1 0 9 7 6 0 6 0 6 0 5 7 2 5 3 3 7 3 0 6 3 9 6 2 8 4 5 7
 1 6 7 5 2 4 5 3 5 1 8 9 4]
0
9
(array([ 0,  4,  8, 11, 30, 48]),)


In [119]:
a = np.random.randint(10, size=6) 
print(a.tolist())
print(list(a))


b = np.random.randint(10, size=(3,4)) 
print(b.tolist())
b1 = list(b)





c = np.random.randint(10, size=(2,3,2)) 
print(c.tolist())
print(list(c))

[0, 3, 4, 0, 3, 1]
[0, 3, 4, 0, 3, 1]
[[8, 1, 9, 8], [8, 3, 5, 6], [9, 1, 6, 2]]
[[[0, 3], [0, 8], [0, 6]], [[6, 6], [6, 2], [7, 2]]]
[array([[0, 3],
       [0, 8],
       [0, 6]]), array([[6, 6],
       [6, 2],
       [7, 2]])]


In [121]:
print(list(a))

b_list = []
for arr in b1:
    new_arr = list(arr)
    b_list.append(new_arr)
print(b_list)

c_list = []
c_new_list = []
for array in c_new:
    for arr in array:
        c_list.append(list(arr))
    c_new_list.append(c_list)
    c_list = []

print(c_new_list)

[0, 3, 4, 0, 3, 1]
[[8, 1, 9, 8], [8, 3, 5, 6], [9, 1, 6, 2]]
[[[8, 1], [9, 0], [5, 7]], [[0, 0], [2, 5], [5, 7]]]


In [125]:
array1 = np.array([[10, 8], [3, 5]])
array2 = np.linalg.inv(array1)
print(array1.dot(array2)) #是

[[1. 0.]
 [0. 1.]]


In [128]:
feature = np.linalg.eig(array1)
print(feature[0]) #特徵值
print(feature[1]) #特徵向量

[13.  2.]
[[ 0.93632918 -0.70710678]
 [ 0.35112344  0.70710678]]


In [137]:
u, s, vh = np.linalg.svd(array1)
print(u, s, vh)

[[-0.91663818 -0.39971796]
 [-0.39971796  0.91663818]] [13.94721714  1.86417116] [[-0.74319741 -0.6690722 ]
 [-0.6690722   0.74319741]]
