In [36]:
import numpy as np

In [50]:
a = np.arange(0,21,1)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [63]:
a = np.arange(0,21,1)
b = a[0:21:2]
print(b)

[ 0  2  4  6  8 10 12 14 16 18 20]


In [64]:
a = np.arange(0,21,1)
c = a[0:21:3]
print(c)

[ 0  3  6  9 12 15 18]
